@WalkForum.API_HostAddress = https://localhost:7227

GET {{WalkForum.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WalkForum.API_HostAddress}}/api/posts?category=Carnets%20de%20marche

###

GET {{WalkForum.API_HostAddress}}/api/posts/17

###

POST {{WalkForum.API_HostAddress}}/api/posts
Content-Type: application/json

{
  "Title" : "T",
  "Content" : "testtest",
  "AuthorId": 1,
  "CategoryId": 3
}

###

DELETE {{WalkForum.API_HostAddress}}/api/posts/12

###

PATCH {{WalkForum.API_HostAddress}}/api/posts/12
Content-Type: application/json

{
  "Title" : "modif de la 12",
  "Content" : "je modifie la 12"
}